# Generated by Django 4.1.3 on 2022-11-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('statuses', models.IntegerField(choices=[(1, 'Correct'), (0, 'Incorrect')])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('answers_number', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
