# Generated by Django 4.1.3 on 2022-11-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='app/static/img/korgi.jpg', upload_to='app/static/img/avatars')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=77, unique=True)),
                ('text', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='app.member')),
                ('dislike_users', models.ManyToManyField(blank=True, related_name='question_dislikes', to='app.member')),
                ('like_users', models.ManyToManyField(blank=True, related_name='question_likes', to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('questions', models.ManyToManyField(related_name='tags', to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='app.member')),
                ('dislike_users', models.ManyToManyField(blank=True, related_name='answer_dislikes', to='app.member')),
                ('like_users', models.ManyToManyField(blank=True, related_name='answer_likes', to='app.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='app.question')),
            ],
        ),
    ]
