# Generated by Django 4.1.3 on 2022-11-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default='app/static/img/korgi.jpg', upload_to='../static/img/avatars'),
        ),
    ]
